"""empty message

Revision ID: a2f428ab114d
Revises: d73b97181f0e
Create Date: 2024-05-04 22:30:32.353318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f428ab114d'
down_revision = 'd73b97181f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('flights')
    with op.batch_alter_table('icao_codes', schema=None) as batch_op:
        batch_op.alter_column('icao',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('icao_codes', schema=None) as batch_op:
        batch_op.alter_column('icao',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)

    op.create_table('flights',
    sa.Column('flightid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('planemodel', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('flightid', name='flights_pkey')
    )
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
