"""empty message

Revision ID: a55ea62696da
Revises: 
Create Date: 2024-05-13 12:50:44.398399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55ea62696da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    op.drop_table('countries')
    with op.batch_alter_table('icao_codes', schema=None) as batch_op:
        batch_op.alter_column('icao',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('icao_codes', schema=None) as batch_op:
        batch_op.alter_column('icao',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)

    op.create_table('countries',
    sa.Column('code', sa.CHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('code', name='countries_pkey')
    )
    op.create_table('flights',
    sa.Column('flightid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('planemodel', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('flightid', name='flights_pkey')
    )
    # ### end Alembic commands ###
